/**
 * Common Constants
 */

export const HTTP_STATUS = {
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    INTERNAL_SERVER_ERROR: 500,
    SERVICE_UNAVAILABLE: 503,
} as const;

export const ERROR_CODES = {
    // Auth errors
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    USERNAME_ALREADY_EXISTS: 'USERNAME_ALREADY_EXISTS',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',

    // Resource errors
    NOT_FOUND: 'NOT_FOUND',
    ALREADY_EXISTS: 'ALREADY_EXISTS',

    // Validation errors
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_INPUT: 'INVALID_INPUT',

    // Tournament errors
    TOURNAMENT_FULL: 'TOURNAMENT_FULL',
    TOURNAMENT_STARTED: 'TOURNAMENT_STARTED',
    ALREADY_REGISTERED: 'ALREADY_REGISTERED',
    INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',

    // Generic errors
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export const DEFAULT_PAGINATION = {
    PAGE: 1,
    LIMIT: 20,
    MAX_LIMIT: 100,
} as const;

export const CACHE_TTL = {
    SHORT: 60, // 1 minute
    MEDIUM: 300, // 5 minutes
    LONG: 3600, // 1 hour
    VERY_LONG: 86400, // 24 hours
} as const;

export const TOURNAMENT_DEFAULTS = {
    STARTING_CHIPS: 10000,
    PLAYERS_PER_TABLE: 8,
    MAX_PLAYERS: 100,
    MIN_PLAYERS: 10,
    LEVEL_DURATION_MINUTES: 15,
    BREAK_FREQUENCY: 4,
    BREAK_DURATION_MINUTES: 10,
    PRIZE_POOL_PERCENTAGE: 100,
} as const;

export default {
    HTTP_STATUS,
    ERROR_CODES,
    DEFAULT_PAGINATION,
    CACHE_TTL,
    TOURNAMENT_DEFAULTS,
};
